server:
  port: 9001

#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
##  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.study.entity
#
##showSql
#logging:
#  level:
#    com:
#      example:
#        mapper : debug